// @ts-check
/**
 * Curated Turkish → English source deck (MVP). Authored order within each unit,
 * and unit order, together define frequency priority — `build-deck.mjs` assigns
 * `freqRank` sequentially across the whole deck in this order, so the most
 * useful words/chunks are introduced first.
 *
 * Entry `id`s here are unit-local slugs; the build prefixes them (`e_<unit>_<id>`)
 * for global, stable ids. NEVER rename an id once shipped — that breaks the
 * SRS reconcile contract. Add new entries at the end of a unit instead.
 *
 * `type`: 'word' | 'phrase' | 'chunk'. Chunks are the formulaic expressions the
 * methodology prioritises over rare vocabulary.
 */

export const meta = {
  version: '2026.07.1',
  language: { code: 'tr', name: 'Turkish' },
};

/** @type {{ id: string, title: string, entries: any[] }[]} */
export const units = [
  {
    id: 'greetings',
    title: 'Greetings & Politeness',
    entries: [
      { id: 'merhaba', tr: 'merhaba', en: 'hello', pos: 'interjection', type: 'word', tags: ['greeting', 'a1'], examples: [{ tr: 'Merhaba, nasılsın?', en: 'Hello, how are you?' }] },
      { id: 'selam', tr: 'selam', en: 'hi', pos: 'interjection', type: 'word', tags: ['greeting', 'informal'], examples: [{ tr: 'Selam! Ne haber?', en: 'Hi! What’s up?' }] },
      { id: 'gunaydin', tr: 'günaydın', en: 'good morning', pos: 'interjection', type: 'word', tags: ['greeting'], examples: [{ tr: 'Günaydın! İyi uyudun mu?', en: 'Good morning! Did you sleep well?' }] },
      { id: 'iyi-gunler', tr: 'iyi günler', en: 'good day / hello', pos: 'phrase', type: 'chunk', tags: ['greeting'], examples: [{ tr: 'İyi günler efendim.', en: 'Good day, sir/madam.' }] },
      { id: 'iyi-aksamlar', tr: 'iyi akşamlar', en: 'good evening', pos: 'phrase', type: 'chunk', tags: ['greeting'], examples: [{ tr: 'İyi akşamlar, hoş geldiniz.', en: 'Good evening, welcome.' }] },
      { id: 'iyi-geceler', tr: 'iyi geceler', en: 'good night', pos: 'phrase', type: 'chunk', tags: ['greeting'], examples: [{ tr: 'İyi geceler, yarın görüşürüz.', en: 'Good night, see you tomorrow.' }] },
      { id: 'hosca-kal', tr: 'hoşça kal', en: 'goodbye (to person staying)', pos: 'phrase', type: 'chunk', tags: ['greeting'], notes: 'Said by the person leaving.', examples: [{ tr: 'Hoşça kal, kendine iyi bak.', en: 'Goodbye, take care.' }] },
      { id: 'gule-gule', tr: 'güle güle', en: 'goodbye (to person leaving)', pos: 'phrase', type: 'chunk', tags: ['greeting'], notes: 'Said by the person staying.', examples: [{ tr: 'Güle güle, yine bekleriz.', en: 'Goodbye, come again.' }] },
      { id: 'gorusuruz', tr: 'görüşürüz', en: 'see you', pos: 'interjection', type: 'chunk', tags: ['greeting'], examples: [{ tr: 'Görüşürüz, iyi günler!', en: 'See you, have a nice day!' }] },
      { id: 'tesekkur-ederim', tr: 'teşekkür ederim', en: 'thank you', pos: 'phrase', type: 'chunk', tags: ['politeness', 'a1'], examples: [{ tr: 'Yardımın için teşekkür ederim.', en: 'Thank you for your help.' }] },
      { id: 'tesekkurler', tr: 'teşekkürler', en: 'thanks', pos: 'interjection', type: 'word', tags: ['politeness'], examples: [{ tr: 'Çok teşekkürler!', en: 'Thanks a lot!' }] },
      { id: 'sagol', tr: 'sağ ol', en: 'thanks (informal)', pos: 'phrase', type: 'chunk', tags: ['politeness', 'informal'], examples: [{ tr: 'Sağ ol dostum.', en: 'Thanks, buddy.' }] },
      { id: 'rica-ederim', tr: 'rica ederim', en: 'you’re welcome', pos: 'phrase', type: 'chunk', tags: ['politeness'], examples: [{ tr: 'Rica ederim, ne demek.', en: 'You’re welcome, don’t mention it.' }] },
      { id: 'bir-sey-degil', tr: 'bir şey değil', en: 'you’re welcome / it’s nothing', pos: 'phrase', type: 'chunk', tags: ['politeness'], examples: [{ tr: 'Teşekkürler! — Bir şey değil.', en: 'Thanks! — It’s nothing.' }] },
      { id: 'lutfen', tr: 'lütfen', en: 'please', pos: 'adverb', type: 'word', tags: ['politeness', 'a1'], examples: [{ tr: 'Bir su, lütfen.', en: 'A water, please.' }] },
      { id: 'affedersiniz', tr: 'affedersiniz', en: 'excuse me (formal)', pos: 'phrase', type: 'chunk', tags: ['politeness'], examples: [{ tr: 'Affedersiniz, saat kaç?', en: 'Excuse me, what time is it?' }] },
      { id: 'pardon', tr: 'pardon', en: 'sorry / excuse me', pos: 'interjection', type: 'word', tags: ['politeness'], examples: [{ tr: 'Pardon, geçebilir miyim?', en: 'Excuse me, may I pass?' }] },
      { id: 'ozur-dilerim', tr: 'özür dilerim', en: 'I’m sorry', pos: 'phrase', type: 'chunk', tags: ['politeness'], examples: [{ tr: 'Geciktim, özür dilerim.', en: 'I’m late, I’m sorry.' }] },
      { id: 'nasilsin', tr: 'nasılsın?', en: 'how are you? (informal)', pos: 'phrase', type: 'chunk', tags: ['smalltalk', 'a1'], examples: [{ tr: 'Merhaba, nasılsın?', en: 'Hi, how are you?' }] },
      { id: 'nasilsiniz', tr: 'nasılsınız?', en: 'how are you? (formal)', pos: 'phrase', type: 'chunk', tags: ['smalltalk'], examples: [{ tr: 'Hoş geldiniz, nasılsınız?', en: 'Welcome, how are you?' }] },
      { id: 'iyiyim', tr: 'iyiyim', en: 'I’m good', pos: 'phrase', type: 'chunk', tags: ['smalltalk'], examples: [{ tr: 'İyiyim, sen nasılsın?', en: 'I’m good, how are you?' }] },
      { id: 'memnun-oldum', tr: 'memnun oldum', en: 'nice to meet you', pos: 'phrase', type: 'chunk', tags: ['smalltalk'], examples: [{ tr: 'Ben Ali. — Memnun oldum!', en: 'I’m Ali. — Nice to meet you!' }] },
    ],
  },
  {
    id: 'essentials',
    title: 'Everyday Essentials',
    entries: [
      { id: 'evet', tr: 'evet', en: 'yes', pos: 'adverb', type: 'word', tags: ['core', 'a1'], examples: [{ tr: 'Evet, doğru.', en: 'Yes, that’s right.' }] },
      { id: 'hayir', tr: 'hayır', en: 'no', pos: 'adverb', type: 'word', tags: ['core', 'a1'], examples: [{ tr: 'Hayır, teşekkürler.', en: 'No, thank you.' }] },
      { id: 'tamam', tr: 'tamam', en: 'okay', pos: 'adverb', type: 'word', tags: ['core'], examples: [{ tr: 'Tamam, anlaştık.', en: 'Okay, agreed.' }] },
      { id: 'belki', tr: 'belki', en: 'maybe', pos: 'adverb', type: 'word', tags: ['core'], examples: [{ tr: 'Belki yarın gelirim.', en: 'Maybe I’ll come tomorrow.' }] },
      { id: 'tabii', tr: 'tabii', en: 'of course', pos: 'adverb', type: 'word', tags: ['core'], examples: [{ tr: 'Tabii, memnuniyetle.', en: 'Of course, with pleasure.' }] },
      { id: 've', tr: 've', en: 'and', pos: 'conjunction', type: 'word', tags: ['core'], examples: [{ tr: 'Çay ve kahve.', en: 'Tea and coffee.' }] },
      { id: 'ama', tr: 'ama', en: 'but', pos: 'conjunction', type: 'word', tags: ['core'], examples: [{ tr: 'İstiyorum ama vaktim yok.', en: 'I want to but I have no time.' }] },
      { id: 'cok', tr: 'çok', en: 'very / a lot', pos: 'adverb', type: 'word', tags: ['core', 'a1'], examples: [{ tr: 'Çok güzel!', en: 'Very nice!' }] },
      { id: 'biraz', tr: 'biraz', en: 'a little', pos: 'adverb', type: 'word', tags: ['core'], examples: [{ tr: 'Biraz Türkçe biliyorum.', en: 'I know a little Turkish.' }] },
      { id: 'var', tr: 'var', en: 'there is / to have', pos: 'verb', type: 'word', tags: ['core', 'a1'], examples: [{ tr: 'Menü var mı?', en: 'Is there a menu?' }] },
      { id: 'yok', tr: 'yok', en: 'there isn’t / not have', pos: 'verb', type: 'word', tags: ['core', 'a1'], examples: [{ tr: 'Vaktim yok.', en: 'I have no time.' }] },
      { id: 'bu', tr: 'bu', en: 'this', pos: 'pronoun', type: 'word', tags: ['core'], examples: [{ tr: 'Bu ne?', en: 'What is this?' }] },
      { id: 'su', tr: 'şu', en: 'that', pos: 'pronoun', type: 'word', tags: ['core'], examples: [{ tr: 'Şu ne kadar?', en: 'How much is that?' }] },
      { id: 'burada', tr: 'burada', en: 'here', pos: 'adverb', type: 'word', tags: ['core'], examples: [{ tr: 'Otobüs burada durur.', en: 'The bus stops here.' }] },
      { id: 'orada', tr: 'orada', en: 'there', pos: 'adverb', type: 'word', tags: ['core'], examples: [{ tr: 'Tuvalet orada.', en: 'The toilet is there.' }] },
      { id: 'simdi', tr: 'şimdi', en: 'now', pos: 'adverb', type: 'word', tags: ['time'], examples: [{ tr: 'Şimdi gidiyorum.', en: 'I’m going now.' }] },
      { id: 'sonra', tr: 'sonra', en: 'later / after', pos: 'adverb', type: 'word', tags: ['time'], examples: [{ tr: 'Sonra konuşuruz.', en: 'We’ll talk later.' }] },
      { id: 'bugun', tr: 'bugün', en: 'today', pos: 'adverb', type: 'word', tags: ['time'], examples: [{ tr: 'Bugün çok yorgunum.', en: 'I’m very tired today.' }] },
      { id: 'yarin', tr: 'yarın', en: 'tomorrow', pos: 'adverb', type: 'word', tags: ['time'], examples: [{ tr: 'Yarın görüşürüz.', en: 'See you tomorrow.' }] },
      { id: 'dun', tr: 'dün', en: 'yesterday', pos: 'adverb', type: 'word', tags: ['time'], examples: [{ tr: 'Dün buradaydım.', en: 'I was here yesterday.' }] },
    ],
  },
  {
    id: 'people',
    title: 'People & Pronouns',
    entries: [
      { id: 'ben', tr: 'ben', en: 'I', pos: 'pronoun', type: 'word', tags: ['pronoun', 'a1'], examples: [{ tr: 'Ben Ayşe.', en: 'I’m Ayşe.' }] },
      { id: 'sen', tr: 'sen', en: 'you (informal)', pos: 'pronoun', type: 'word', tags: ['pronoun', 'a1'], examples: [{ tr: 'Sen nerelisin?', en: 'Where are you from?' }] },
      { id: 'siz', tr: 'siz', en: 'you (formal / plural)', pos: 'pronoun', type: 'word', tags: ['pronoun'], examples: [{ tr: 'Siz nereden geliyorsunuz?', en: 'Where are you coming from?' }] },
      { id: 'biz', tr: 'biz', en: 'we', pos: 'pronoun', type: 'word', tags: ['pronoun'], examples: [{ tr: 'Biz turistiz.', en: 'We are tourists.' }] },
      { id: 'onlar', tr: 'onlar', en: 'they', pos: 'pronoun', type: 'word', tags: ['pronoun'], examples: [{ tr: 'Onlar arkadaşım.', en: 'They are my friends.' }] },
      { id: 'benim-adim', tr: 'benim adım …', en: 'my name is …', pos: 'phrase', type: 'chunk', tags: ['intro', 'a1'], examples: [{ tr: 'Benim adım Deniz.', en: 'My name is Deniz.' }] },
      { id: 'adin-ne', tr: 'adın ne?', en: 'what’s your name?', pos: 'phrase', type: 'chunk', tags: ['intro', 'a1'], examples: [{ tr: 'Merhaba, adın ne?', en: 'Hi, what’s your name?' }] },
      { id: 'anne', tr: 'anne', en: 'mother', pos: 'noun', type: 'word', tags: ['family'], examples: [{ tr: 'Bu benim annem.', en: 'This is my mother.' }] },
      { id: 'baba', tr: 'baba', en: 'father', pos: 'noun', type: 'word', tags: ['family'], examples: [{ tr: 'Babam doktor.', en: 'My father is a doctor.' }] },
      { id: 'arkadas', tr: 'arkadaş', en: 'friend', pos: 'noun', type: 'word', tags: ['people'], examples: [{ tr: 'O benim arkadaşım.', en: 'That’s my friend.' }] },
      { id: 'cocuk', tr: 'çocuk', en: 'child', pos: 'noun', type: 'word', tags: ['people'], examples: [{ tr: 'İki çocuğum var.', en: 'I have two children.' }] },
      { id: 'kadin', tr: 'kadın', en: 'woman', pos: 'noun', type: 'word', tags: ['people'], examples: [{ tr: 'O kadın öğretmen.', en: 'That woman is a teacher.' }] },
      { id: 'adam', tr: 'adam', en: 'man', pos: 'noun', type: 'word', tags: ['people'], examples: [{ tr: 'Bu adam kim?', en: 'Who is this man?' }] },
    ],
  },
  {
    id: 'questions',
    title: 'Asking Questions',
    entries: [
      { id: 'ne', tr: 'ne', en: 'what', pos: 'pronoun', type: 'word', tags: ['question', 'a1'], examples: [{ tr: 'Bu ne?', en: 'What is this?' }] },
      { id: 'kim', tr: 'kim', en: 'who', pos: 'pronoun', type: 'word', tags: ['question'], examples: [{ tr: 'O kim?', en: 'Who is that?' }] },
      { id: 'nerede', tr: 'nerede', en: 'where', pos: 'adverb', type: 'word', tags: ['question', 'a1'], examples: [{ tr: 'Otel nerede?', en: 'Where is the hotel?' }] },
      { id: 'ne-zaman', tr: 'ne zaman', en: 'when', pos: 'adverb', type: 'chunk', tags: ['question'], examples: [{ tr: 'Tren ne zaman gelir?', en: 'When does the train come?' }] },
      { id: 'neden', tr: 'neden', en: 'why', pos: 'adverb', type: 'word', tags: ['question'], examples: [{ tr: 'Neden geç kaldın?', en: 'Why are you late?' }] },
      { id: 'nasil', tr: 'nasıl', en: 'how', pos: 'adverb', type: 'word', tags: ['question'], examples: [{ tr: 'Bu nasıl çalışır?', en: 'How does this work?' }] },
      { id: 'kac', tr: 'kaç', en: 'how many', pos: 'adjective', type: 'word', tags: ['question'], examples: [{ tr: 'Kaç yaşındasın?', en: 'How old are you?' }] },
      { id: 'ne-kadar', tr: 'ne kadar', en: 'how much', pos: 'phrase', type: 'chunk', tags: ['question', 'shopping'], examples: [{ tr: 'Bu ne kadar?', en: 'How much is this?' }] },
      { id: 'hangi', tr: 'hangi', en: 'which', pos: 'adjective', type: 'word', tags: ['question'], examples: [{ tr: 'Hangi otobüs?', en: 'Which bus?' }] },
      { id: 'ne-demek', tr: 'ne demek?', en: 'what does it mean?', pos: 'phrase', type: 'chunk', tags: ['question', 'learning'], examples: [{ tr: '“Yavaş” ne demek?', en: 'What does “yavaş” mean?' }] },
      { id: 'anlamadim', tr: 'anlamadım', en: 'I didn’t understand', pos: 'phrase', type: 'chunk', tags: ['learning', 'a1'], examples: [{ tr: 'Pardon, anlamadım.', en: 'Sorry, I didn’t understand.' }] },
      { id: 'tekrar-eder-misiniz', tr: 'tekrar eder misiniz?', en: 'could you repeat that?', pos: 'phrase', type: 'chunk', tags: ['learning'], examples: [{ tr: 'Tekrar eder misiniz, lütfen?', en: 'Could you repeat that, please?' }] },
      { id: 'yavas-konusur-musunuz', tr: 'yavaş konuşur musunuz?', en: 'could you speak slowly?', pos: 'phrase', type: 'chunk', tags: ['learning'], examples: [{ tr: 'Yavaş konuşur musunuz, lütfen?', en: 'Could you speak slowly, please?' }] },
      { id: 'ingilizce-biliyor-musunuz', tr: 'İngilizce biliyor musunuz?', en: 'do you speak English?', pos: 'phrase', type: 'chunk', tags: ['learning', 'travel'], examples: [{ tr: 'Affedersiniz, İngilizce biliyor musunuz?', en: 'Excuse me, do you speak English?' }] },
      { id: 'turkce-bilmiyorum', tr: 'Türkçe bilmiyorum', en: 'I don’t speak Turkish', pos: 'phrase', type: 'chunk', tags: ['learning', 'travel'], examples: [{ tr: 'Kusura bakmayın, Türkçe bilmiyorum.', en: 'Sorry, I don’t speak Turkish.' }] },
    ],
  },
  {
    id: 'food',
    title: 'Food & Café',
    entries: [
      { id: 'su', tr: 'su', en: 'water', pos: 'noun', type: 'word', tags: ['food', 'a1'], examples: [{ tr: 'Bir su, lütfen.', en: 'A water, please.' }] },
      { id: 'cay', tr: 'çay', en: 'tea', pos: 'noun', type: 'word', tags: ['food', 'a1'], examples: [{ tr: 'Bir çay alabilir miyim?', en: 'Can I get a tea?' }] },
      { id: 'kahve', tr: 'kahve', en: 'coffee', pos: 'noun', type: 'word', tags: ['food'], examples: [{ tr: 'Sütlü kahve, lütfen.', en: 'Coffee with milk, please.' }] },
      { id: 'ekmek', tr: 'ekmek', en: 'bread', pos: 'noun', type: 'word', tags: ['food'], examples: [{ tr: 'Taze ekmek var mı?', en: 'Is there fresh bread?' }] },
      { id: 'yemek', tr: 'yemek', en: 'food / meal', pos: 'noun', type: 'word', tags: ['food'], examples: [{ tr: 'Yemek çok lezzetli.', en: 'The food is very delicious.' }] },
      { id: 'kahvalti', tr: 'kahvaltı', en: 'breakfast', pos: 'noun', type: 'word', tags: ['food'], examples: [{ tr: 'Kahvaltı saat kaçta?', en: 'What time is breakfast?' }] },
      { id: 'hesap', tr: 'hesap', en: 'the bill', pos: 'noun', type: 'word', tags: ['food', 'travel'], examples: [{ tr: 'Hesap, lütfen.', en: 'The bill, please.' }] },
      { id: 'menu', tr: 'menü', en: 'menu', pos: 'noun', type: 'word', tags: ['food'], examples: [{ tr: 'Menüyü alabilir miyim?', en: 'Can I have the menu?' }] },
      { id: 'istiyorum', tr: 'istiyorum', en: 'I want', pos: 'verb', type: 'word', tags: ['core', 'a1'], notes: 'From istemek (to want).', examples: [{ tr: 'Su istiyorum.', en: 'I want water.' }] },
      { id: 'bir-cay-lutfen', tr: 'bir çay, lütfen', en: 'a tea, please', pos: 'phrase', type: 'chunk', tags: ['food', 'a1'], examples: [{ tr: 'Bir çay, lütfen.', en: 'A tea, please.' }] },
      { id: 'hesap-lutfen', tr: 'hesap, lütfen', en: 'the bill, please', pos: 'phrase', type: 'chunk', tags: ['food'], examples: [{ tr: 'Hesap, lütfen.', en: 'The bill, please.' }] },
      { id: 'afiyet-olsun', tr: 'afiyet olsun', en: 'enjoy your meal', pos: 'phrase', type: 'chunk', tags: ['food'], examples: [{ tr: 'Buyurun, afiyet olsun.', en: 'Here you go, enjoy your meal.' }] },
      { id: 'ac', tr: 'aç', en: 'hungry', pos: 'adjective', type: 'word', tags: ['food'], examples: [{ tr: 'Çok açım.', en: 'I’m very hungry.' }] },
      { id: 'susadim', tr: 'susadım', en: 'I’m thirsty', pos: 'phrase', type: 'chunk', tags: ['food'], examples: [{ tr: 'Susadım, su var mı?', en: 'I’m thirsty, is there water?' }] },
      { id: 'lezzetli', tr: 'lezzetli', en: 'delicious', pos: 'adjective', type: 'word', tags: ['food'], examples: [{ tr: 'Çok lezzetli, teşekkürler.', en: 'Very delicious, thank you.' }] },
    ],
  },
  {
    id: 'numbers',
    title: 'Numbers & Time',
    entries: [
      { id: 'bir', tr: 'bir', en: 'one / a', pos: 'numeral', type: 'word', tags: ['number', 'a1'], examples: [{ tr: 'Bir kahve, lütfen.', en: 'One coffee, please.' }] },
      { id: 'iki', tr: 'iki', en: 'two', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'İki kişi.', en: 'Two people.' }] },
      { id: 'uc', tr: 'üç', en: 'three', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'Üç gün kaldım.', en: 'I stayed three days.' }] },
      { id: 'dort', tr: 'dört', en: 'four', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'Saat dört.', en: 'It’s four o’clock.' }] },
      { id: 'bes', tr: 'beş', en: 'five', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'Beş dakika.', en: 'Five minutes.' }] },
      { id: 'alti', tr: 'altı', en: 'six', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'Altı kişiyiz.', en: 'We are six people.' }] },
      { id: 'yedi', tr: 'yedi', en: 'seven', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'Yedi gün.', en: 'Seven days.' }] },
      { id: 'sekiz', tr: 'sekiz', en: 'eight', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'Saat sekizde.', en: 'At eight o’clock.' }] },
      { id: 'dokuz', tr: 'dokuz', en: 'nine', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'Dokuz numara.', en: 'Number nine.' }] },
      { id: 'on', tr: 'on', en: 'ten', pos: 'numeral', type: 'word', tags: ['number'], examples: [{ tr: 'On lira.', en: 'Ten lira.' }] },
      { id: 'saat', tr: 'saat', en: 'hour / clock', pos: 'noun', type: 'word', tags: ['time'], examples: [{ tr: 'Bir saat sonra.', en: 'In one hour.' }] },
      { id: 'saat-kac', tr: 'saat kaç?', en: 'what time is it?', pos: 'phrase', type: 'chunk', tags: ['time', 'a1'], examples: [{ tr: 'Affedersiniz, saat kaç?', en: 'Excuse me, what time is it?' }] },
      { id: 'dakika', tr: 'dakika', en: 'minute', pos: 'noun', type: 'word', tags: ['time'], examples: [{ tr: 'Beş dakika bekle.', en: 'Wait five minutes.' }] },
      { id: 'gun', tr: 'gün', en: 'day', pos: 'noun', type: 'word', tags: ['time'], examples: [{ tr: 'Güzel bir gün.', en: 'A beautiful day.' }] },
      { id: 'hafta', tr: 'hafta', en: 'week', pos: 'noun', type: 'word', tags: ['time'], examples: [{ tr: 'Gelecek hafta.', en: 'Next week.' }] },
    ],
  },
  {
    id: 'around',
    title: 'Getting Around',
    entries: [
      { id: 'tuvalet', tr: 'tuvalet', en: 'toilet', pos: 'noun', type: 'word', tags: ['travel', 'a1'], examples: [{ tr: 'Tuvalet nerede?', en: 'Where is the toilet?' }] },
      { id: 'tuvalet-nerede', tr: 'tuvalet nerede?', en: 'where is the toilet?', pos: 'phrase', type: 'chunk', tags: ['travel', 'a1'], examples: [{ tr: 'Affedersiniz, tuvalet nerede?', en: 'Excuse me, where is the toilet?' }] },
      { id: 'sol', tr: 'sol', en: 'left', pos: 'noun', type: 'word', tags: ['directions'], examples: [{ tr: 'Soldan git.', en: 'Go from the left.' }] },
      { id: 'sag', tr: 'sağ', en: 'right', pos: 'noun', type: 'word', tags: ['directions'], examples: [{ tr: 'Sağa dön.', en: 'Turn right.' }] },
      { id: 'duz', tr: 'düz', en: 'straight', pos: 'adverb', type: 'word', tags: ['directions'], examples: [{ tr: 'Düz git.', en: 'Go straight.' }] },
      { id: 'yakin', tr: 'yakın', en: 'near', pos: 'adjective', type: 'word', tags: ['directions'], examples: [{ tr: 'Otel yakın mı?', en: 'Is the hotel near?' }] },
      { id: 'uzak', tr: 'uzak', en: 'far', pos: 'adjective', type: 'word', tags: ['directions'], examples: [{ tr: 'Çok uzak mı?', en: 'Is it very far?' }] },
      { id: 'otobus', tr: 'otobüs', en: 'bus', pos: 'noun', type: 'word', tags: ['transport'], examples: [{ tr: 'Otobüs ne zaman gelir?', en: 'When does the bus come?' }] },
      { id: 'taksi', tr: 'taksi', en: 'taxi', pos: 'noun', type: 'word', tags: ['transport'], examples: [{ tr: 'Bir taksi lazım.', en: 'I need a taxi.' }] },
      { id: 'otel', tr: 'otel', en: 'hotel', pos: 'noun', type: 'word', tags: ['travel'], examples: [{ tr: 'Otelim burada.', en: 'My hotel is here.' }] },
      { id: 'bilet', tr: 'bilet', en: 'ticket', pos: 'noun', type: 'word', tags: ['travel'], examples: [{ tr: 'İki bilet, lütfen.', en: 'Two tickets, please.' }] },
      { id: 'ne-kadar-tutar', tr: 'ne kadar tutar?', en: 'how much does it cost?', pos: 'phrase', type: 'chunk', tags: ['shopping', 'travel'], examples: [{ tr: 'Havaalanına ne kadar tutar?', en: 'How much does it cost to the airport?' }] },
      { id: 'kayboldum', tr: 'kayboldum', en: 'I’m lost', pos: 'phrase', type: 'chunk', tags: ['travel'], examples: [{ tr: 'Yardım edin, kayboldum.', en: 'Help, I’m lost.' }] },
    ],
  },
  {
    id: 'feelings',
    title: 'Feelings & Small Talk',
    entries: [
      { id: 'iyi', tr: 'iyi', en: 'good', pos: 'adjective', type: 'word', tags: ['feelings', 'a1'], examples: [{ tr: 'Her şey iyi.', en: 'Everything is good.' }] },
      { id: 'kotu', tr: 'kötü', en: 'bad', pos: 'adjective', type: 'word', tags: ['feelings'], examples: [{ tr: 'Hava çok kötü.', en: 'The weather is very bad.' }] },
      { id: 'guzel', tr: 'güzel', en: 'beautiful / nice', pos: 'adjective', type: 'word', tags: ['feelings', 'a1'], examples: [{ tr: 'Çok güzel bir şehir.', en: 'A very beautiful city.' }] },
      { id: 'mutlu', tr: 'mutlu', en: 'happy', pos: 'adjective', type: 'word', tags: ['feelings'], examples: [{ tr: 'Çok mutluyum.', en: 'I’m very happy.' }] },
      { id: 'yorgun', tr: 'yorgun', en: 'tired', pos: 'adjective', type: 'word', tags: ['feelings'], examples: [{ tr: 'Bugün çok yorgunum.', en: 'I’m very tired today.' }] },
      { id: 'hasta', tr: 'hasta', en: 'sick', pos: 'adjective', type: 'word', tags: ['feelings'], examples: [{ tr: 'Biraz hastayım.', en: 'I’m a little sick.' }] },
      { id: 'harika', tr: 'harika', en: 'great / wonderful', pos: 'adjective', type: 'word', tags: ['feelings'], examples: [{ tr: 'Harika bir fikir!', en: 'A wonderful idea!' }] },
      { id: 'nereli-siniz', tr: 'nerelisiniz?', en: 'where are you from?', pos: 'phrase', type: 'chunk', tags: ['smalltalk', 'a1'], examples: [{ tr: 'Memnun oldum, nerelisiniz?', en: 'Nice to meet you, where are you from?' }] },
      { id: 'turkce', tr: 'Türkçe', en: 'Turkish (language)', pos: 'noun', type: 'word', tags: ['learning'], examples: [{ tr: 'Türkçe öğreniyorum.', en: 'I’m learning Turkish.' }] },
      { id: 'ingilizce', tr: 'İngilizce', en: 'English (language)', pos: 'noun', type: 'word', tags: ['learning'], examples: [{ tr: 'İngilizce konuşuyorum.', en: 'I speak English.' }] },
      { id: 'cok-guzel', tr: 'çok güzel', en: 'very nice', pos: 'phrase', type: 'chunk', tags: ['smalltalk'], examples: [{ tr: 'Bu yemek çok güzel.', en: 'This food is very nice.' }] },
      { id: 'gercekten-mi', tr: 'gerçekten mi?', en: 'really?', pos: 'phrase', type: 'chunk', tags: ['smalltalk'], examples: [{ tr: 'Gerçekten mi? İnanmıyorum!', en: 'Really? I don’t believe it!' }] },
    ],
  },
  {
    id: 'verbs',
    title: 'Core Verbs & Useful Chunks',
    entries: [
      { id: 'gitmek', tr: 'gitmek', en: 'to go', pos: 'verb', type: 'word', tags: ['verb', 'a1'], examples: [{ tr: 'Eve gitmek istiyorum.', en: 'I want to go home.' }] },
      { id: 'gelmek', tr: 'gelmek', en: 'to come', pos: 'verb', type: 'word', tags: ['verb'], examples: [{ tr: 'Yarın gel.', en: 'Come tomorrow.' }] },
      { id: 'icmek', tr: 'içmek', en: 'to drink', pos: 'verb', type: 'word', tags: ['verb'], examples: [{ tr: 'Çay içmek ister misin?', en: 'Do you want to drink tea?' }] },
      { id: 'yapmak', tr: 'yapmak', en: 'to do / make', pos: 'verb', type: 'word', tags: ['verb'], examples: [{ tr: 'Ne yapıyorsun?', en: 'What are you doing?' }] },
      { id: 'gormek', tr: 'görmek', en: 'to see', pos: 'verb', type: 'word', tags: ['verb'], examples: [{ tr: 'Seni görmek güzel.', en: 'It’s nice to see you.' }] },
      { id: 'bilmek', tr: 'bilmek', en: 'to know', pos: 'verb', type: 'word', tags: ['verb'], examples: [{ tr: 'Yolu biliyor musun?', en: 'Do you know the way?' }] },
      { id: 'konusmak', tr: 'konuşmak', en: 'to speak', pos: 'verb', type: 'word', tags: ['verb'], examples: [{ tr: 'Türkçe konuşmak istiyorum.', en: 'I want to speak Turkish.' }] },
      { id: 'anlamak', tr: 'anlamak', en: 'to understand', pos: 'verb', type: 'word', tags: ['verb'], examples: [{ tr: 'Anlıyorum.', en: 'I understand.' }] },
      { id: 'biliyorum', tr: 'biliyorum', en: 'I know', pos: 'verb', type: 'chunk', tags: ['a1'], examples: [{ tr: 'Evet, biliyorum.', en: 'Yes, I know.' }] },
      { id: 'bilmiyorum', tr: 'bilmiyorum', en: 'I don’t know', pos: 'phrase', type: 'chunk', tags: ['a1'], examples: [{ tr: 'Kusura bakma, bilmiyorum.', en: 'Sorry, I don’t know.' }] },
      { id: 'var-mi', tr: '… var mı?', en: 'is there …?', pos: 'phrase', type: 'chunk', tags: ['a1'], examples: [{ tr: 'Boş masa var mı?', en: 'Is there a free table?' }] },
      { id: 'yardim-eder-misiniz', tr: 'yardım eder misiniz?', en: 'can you help me?', pos: 'phrase', type: 'chunk', tags: ['travel'], examples: [{ tr: 'Affedersiniz, yardım eder misiniz?', en: 'Excuse me, can you help me?' }] },
    ],
  },
];
